name: Test pipeline

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - 'v*' # this tag type is used for release pipelines

jobs:
  test-pipeline:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN:  ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - uses: actions/checkout@v1

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7.5

      - name: Install pip
        run: |
          python -m pip install --upgrade pip
          pip install databricks-cli

      - name: Install dependencies and project in dev mode
        run: |
          pip install -e .

      - name: Deploy notebooks
        shell: bash
        run: |
          echo "Deploying python code"
          databricks workspace import_dir --overwrite cicd_harry/jobs/ /Shared/cicd_harry/jobs



